version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    
    php:
        build:
            ./docker/php
        working_dir: /src
        volumes:
            - ./src:/src
            - ./docker/php/datezone.ini:/usr/local/etc/php/conf.d/datezone.ini
        depends_on:
            - db
    
    db:
        image: mysql:5.6
        command: --init-file /data/application/init.sql
        restart: always
        volumes:
            - ./docker/mysql/init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: qW1234